### ISSUE TITLE
Crash of modal navigation

### ISSUE THREAD

**Issue by georgemark0v** [nativescript-community/ui-collectionview#13]
"@nativescript-community/ui-collectionview": "^4.0.9",
"@nativescript-community/ui-collectionview-waterfall": "^1.1.0"
"@nativescript/ios": "7.0.6"

I have nested collection views 
• Displayed messages ;
• Displayed attachments with waterfall layout;

The problem is that after I have opened page where one collection is nested in another, modals stop working until you open any other page. In the console, the following error: **_Could not find parent with viewController for CollectionView (652) while showing modal view._**

The same is observed when the collection is located in UITableView cell.

Video example: https://yadi.sk/i/pV8NNdtioyg50g

**Comment by farfromrefug** [comment]
Please share a full error stack. And a repro example would be nice
