### ISSUE TITLE
Feature Request: Scroll Snap Items

### ISSUE THREAD

**Issue by aPinix** [nativescript-community/ui-collectionview#15]
It would be awesome if `CollectionView` could have the ability to snap items (1 or more).

https://user-images.githubusercontent.com/698523/105027761-10be8a80-5a48-11eb-8019-e82ea12546a2.mp4

**Comment by liamcharmer** [comment]
Is there anything regarding this?

**Comment by farfromrefug** [comment]
you should a use a pager for this
