### ISSUE TITLE
Row height change documentation

### ISSUE THREAD

**Issue by vallemar** [nativescript-community/ui-collectionview#20]
I have experienced a problem that can be very common.  Let's imagine that I have 2 templates: header and item.  Inside the header or the item I have something that is interactive: if you touch a button the row shows something new and therefore the height changes.  when this behavior happens in android it works fine, the row is enlarged but in iOS the final ones overflow and do "strange things".  I have tried refresh () but with no luck.  Could there be an example in the documentation for what to do in this case?  I have not been able to solve it and I have created another view with the detail.  I do not want a solution for myself, what I would like is that the next one who arrives does not spend hours like me for this.

**Comment by farfromrefug** [comment]
You need to call `setItem` on a `ObservableArray` and change a variable in your item which would be used to define the item height (dont use `rowHeight`).
As for documenting this, it is a good Idea and you are welcome to create a PR. (sorry dont have enough time to maintain all plugins, write my apps and do docs on top of that ;))

**Comment by vallemar** [comment]
i think i will try what you are saying but i will try it again with a new project.  If it works I will create a PR with a small section!

**Comment by farfromrefug** [comment]
@vallemar thanks it should work i do that all the time for FAQs

**Comment by vallemar** [comment]
Hi @farfromrefug , I have created the test project. My result is that if you have a condition inside the template and you activate the property of an observableArray that makes it show, this does not happen if you don't force the .refresh() of the list, I put my example code:


```
<template>
  <Page>
    <GridLayout>
      <CollectionView :items="dataItems" ref="list">
        <v-template>
          <StackLayout>
            <Label :text="item.content"></Label>
            <StackLayout v-if="item.open" style="height:400; background:blue">
            </StackLayout>
          </StackLayout>
        </v-template>
      </CollectionView>
    </GridLayout>
  </Page>
</template>

<script lang="ts">
import { ObservableArray } from "@nativescript/core";
import Vue from "nativescript-vue";

export default Vue.extend({
  created() {
    setTimeout(() => {
      this.dataItems.getItem(2).open = true;
      this.$refs.list.nativeView.refresh(); //<--- necessary for the effect to take effect
    }, 2000);
  },
  data() {
    return {
      dataItems: new ObservableArray([
        { content: "any", open: false },
        { content: "any", open: false },
        { content: "any", open: false }
      ])
    };
  }
});
</script>

```

**Comment by farfromrefug** [comment]
@vallemar this is not the right way to update an `ObservableArray`. You need to call `setItem` on the `ObservableArray`

**Comment by vallemar** [comment]
ummm, that would be if your intention is to add a new item to the list but if you want to update an existing element like I do in the example, do you have to force .refresh()?

**Comment by farfromrefug** [comment]
@vallemar no if you want to add you use `splice` or `push` . `setItem` is exactly for what you want. You can look at the typings it should be explained

**Comment by vallemar** [comment]
Ahhh ok, now I understand you. You should do `getItem(x)`, then `modify the object` and then do a `setItem(object, x)`. Personally I don't see setItem as a natural language for a set/update method? and for me it has been confusing. Thank you

**Comment by farfromrefug** [comment]
@vallemar yes no problem i dont really like it either ;)
