### ISSUE TITLE
Feature Request: Add method similar to ListView isItemAtIndexVisible

### ISSUE THREAD

**Issue by garsuga** [nativescript-community/ui-collectionview#23]
I could not find anything similar to this in CollectionView, would it be possible to expose a function similar to the isItemAtIndexVisible function in ListView.  https://v6.docs.nativescript.org/api-reference/classes/_ui_list_view_.listview.html#isitematindexvisible

**Comment by farfromrefug** [comment]
@garsuga added in 4.0.31

**Comment by garsuga** [comment]
Seems to work great, thanks
