### ISSUE TITLE
[Question] - Is ui-collectionview going to replace RadListView?

### ISSUE THREAD

**Issue by bmacdonald** [nativescript-community/ui-collectionview#25]
Hi, I just wanted to know if this component is the replacement for RadListView?

Also, is it a better alternative?

**Comment by farfromrefug** [comment]
@bmacdonald best ask that kind of question in discord. This is a place to report issues and such.
I ll gladly answer you there

**Comment by bmacdonald** [comment]
@farfromrefug - I don't use discord.  It's blocked at work.  Anyhow, I will take it as a no.

**Comment by farfromrefug** [comment]
@bmacdonald no dont take it as a NO :D you can also find us on Slack.
Yes it is a better alternative to RLV. Just some features are not there yet like swipe menu.
Also filtering / grouping needs to be done on the app side (which makes for much better perfs of the plugin)
