### ISSUE TITLE
Feature Request: Multiple Item Selection

### ISSUE THREAD

**Issue by beawolf** [nativescript-community/ui-collectionview#28]
It would be nice to add a multiple item selection feature to this plugin for it to be a full alternative to [RadListView](https://docs.nativescript.org/plugins/nativescript-ui/rad-list-view.html#selection) plugin.

As a side note, both underlying native components (UICollectionView for iOS and RecyclerView for Android) seem to provide this feature on native side.

**Comment by farfromrefug** [comment]
@beawolf i think it will never be part of this plugin. It is really easy to do on the app side and allows all sort of behavior / customisation. Native side provide a very limited selection implementation.
You could however create a plugin on top of this to create your special behavior if you want.
I ll close this as i wont implement this. 
You are welcome to create a plugin. You can do it as a PR  on this repo (monorepo).

**Comment by beawolf** [comment]
I understood, @farfromrefug, fair enough. I use [ui-pulltorefresh](https://github.com/nativescript-community/ui-pulltorefresh) plugin combined with ui-collectionview plugin, for example. A separate plugin would be better maybe, as you said.

Thanks for swift response, btw. :)

**Comment by farfromrefug** [comment]
@beawolf no worries. So we are clear i say selection is very easy to do thanks to observable array.
