### ISSUE TITLE
Feature Request: Scroll Start event

### ISSUE THREAD

**Issue by cjohn001** [nativescript-community/ui-collectionview#32]
It would be great if the collection view could provide a scrollStart event with the scroll direction up/down. I would like to create a sticky header which shall be closed once the view is scrolled up. On scroll start I would like to resize the scrollview in order for it to occupy the vertical space which will become available from the header sliding out of the screen. This would be best done before scrolling starts, as it seems like the layout cycle triggered by resizing the collection view leads to a jump in scrolling when resizing during scrolling. With a scroll start event resizing could be done before entering scrolling.

**Comment by farfromrefug** [comment]
@cjohn001 i just released it https://github.com/nativescript-community/ui-collectionview/commit/809842b7b2e02090bb8e1668169886038ceb5d29

**Comment by cjohn001** [comment]
@farfromrefug : 
Thank you very much. I just tried it out. Works perfectly!
