### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by Echoju** [nativescript-community/ui-collectionview#38]
Hi,

I am having an issue.
I use CollectionView directly in a .vue file and I get this error : 
"[Vue warn]: Failed to mount component: template or render function not defined"

I followed every steps as described in the readme, but no results.
I use the latest versions : 
"@nativescript-community/ui-collectionview": "^4.0.49"
"@nativescript/core": "~8.2.0"
"vue": "~2.6.12"

I use the following code : 

<CollectionView
    :items="itemList"
    colWidth="50%"
    rowHeight="100"
>
    <v-template>
        <Label :text="item.name"></Label>
    </v-template>
</CollectionView>

......
import CollectionView from '@nativescript-community/ui-collectionview/vue';

 components: { 
       CollectionView
    }
    
   Do I have to change something ? Has anyonelse this issue ?
   
   Thanks.

**Comment by farfromrefug** [comment]
@Echoju you are installing it wrong https://github.com/nativescript-community/ui-collectionview#usage-in-vue=

**Comment by Echoju** [comment]
Thanks for your reply !
Could you explain a little more ?
Is it the wrong npm install ? 
To be more clear I also have this in the app.ts => Vue.use(RadSideDrawer,CollectionView)

Thanks.

**Comment by farfromrefug** [comment]
@Echoju this is wrong:
```
import CollectionView from '@nativescript-community/ui-collectionview/vue';

components: {
CollectionView
}
```
please look at the linked documentation

**Comment by Echoju** [comment]
Thanks this was so simple !
I removed this =>
components: {
CollectionView
}

And adde a Vue.use

Thanks a lot !

**Comment by Echoju** [comment]
Hello,
Sorry to bring back this issue.
But I have still a problem with registering the component "CollectionView"
I register my component as expected in my app.ts :

...
import CollectionView from '@nativescript-community/ui-collectionview/vue' 
...
Vue.use(RadSideDrawer,CollectionView,BottomNavigationBar);

But I still have a message as following : 
"[Vue warn]: Unknown custom element: <CollectionView> - did you register the component correctly? For recursive components, make sure to provide the "name" option."

In my component "home.vue" I have this code : 

"<CollectionView class="my_list" :items="liste_items" colWidth="50%" rowHeight="180" width="95%" margin="0" marginLeft="0" paddingLeft="0" > .... </CollectionView />"


Is this normal that the component CollectionView si not recognized ?
Do I have to register the component in every "page" (vue.use) then why register it in the app.ts ?
 
Thanks a lot.

**Comment by Echoju** [comment]
Hello,
Sorry to bring back this issue.
But I have still a problem with registering the component "CollectionView"
I register my component as expected in my app.ts :

...
import CollectionView from '@nativescript-community/ui-collectionview/vue'
...
Vue.use(RadSideDrawer,CollectionView,BottomNavigationBar);

But I still have a message as following :
"[Vue warn]: Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option."

In my component "home.vue" I have this code :

" .... </CollectionView />"

Is this normal that the component CollectionView si not recognized ?
Do I have to register the component in every "page" (vue.use) then why register it in the app.ts ?

Thanks a lot.

**Comment by Echoju** [comment]
I added this in the file app.ts so that the component coumd be "global" :
Vue.component('CollectionView', CollectionView); 

And now it is working fine.

**Comment by farfromrefug** [comment]
@Echoju you can't register them like that. one at a time
