### ISSUE TITLE
Layout issues on iOS with 4.0.60 due to autoReloadItemOnLayout

### ISSUE THREAD

**Issue by hendrickson-tyler** [nativescript-community/ui-collectionview#42]
Updated to the latest 4.0.60 and it seems that the new `autoReloadItemOnLayout` is causing layout issues on iOS (at least for my app). This happens in both the simulator as well as an actual device. Android seems unaffected.

The following screenshot is what the CollectionView looks like when the `autoReloadItemOnLayout` property is not set or is set to `true`. Curiously, this issue corrects itself after rotating the device twice (I'm assuming because it triggers an auto reload). Rotating again after this causes the issue to re-emerge, which requires another two rotations to fix.

![image](https://user-images.githubusercontent.com/6372535/188333926-33962dc7-a532-4912-8ee0-6ab48fd35f03.png)

This is what it looks like with `autoReloadItemOnLayout="false"`. Rotating the device doesn't produce any issues.

![image](https://user-images.githubusercontent.com/6372535/188333992-a9214954-cf46-41f8-bb5d-a7a2890dddd5.png)

Easy fix is just to keep it `false` for now, but is there a reason that this experimental feature is enabled by default?

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.3.2
- Cross-platform modules: 8.3.4
- Plugin(s): "@nativescript-community/ui-collectionview": "4.0.60",

**Comment by farfromrefug** [comment]
@hendrickson-tyler thanks for the report. can you share a repro simple. it was on by default cause it should work :) but i ll disable it by default.

**Comment by farfromrefug** [comment]
@hendrickson-tyler default value changed in new release. By any chance could you still try to reproduce this in a simple example so that i can fix it for good?

**Comment by hendrickson-tyler** [comment]
@farfromrefug Sorry for the late response. Yeah, I'll try to come up with something tonight and share that with you.

**Comment by hendrickson-tyler** [comment]
@farfromrefug I think I've narrowed down the issue a bit. From what I can tell, it seems to be caused by having an `*ngFor` nested inside the CollectionView (like what I'm doing for the specific events above). Something about that is causing it to behave a little weird.

Here's a simple project where you can see the issue:
https://github.com/hendrickson-tyler/collectionview-repro

Hopefully that helps!

**Comment by farfromrefug** [comment]
@hendrickson-tyler sorry for answering late about this. I ran your code but i dont see anything wrong there.
Anyway you should never use a ngFor in a template if it depends on the items props. What you should do is do the ngFor for a fixed length and set the visibility of each one depending on the item. Does that make sense?
The layout is normal in a sense that collectionview does not support that.

**Comment by hendrickson-tyler** [comment]
@farfromrefug Now I'm sorry for my late response 🙂 Sorry, I'm not sure I follow. Could you give an example, maybe? I think no matter what, I have to depend on the items props because I need to know what sub-items (specific events) I need to display for that item. I'm probably misunderstanding though.

I just tested again with `autoReloadItemOnLayout="true"` after a good while (now on v5.1.7) and it looks like there are some different problems. I get multiple errors saying `ERROR TypeError: Cannot read properties of null (reading 'destroyed')` and the view looks like this after rotating:

![image](https://github.com/nativescript-community/ui-collectionview/assets/6372535/ddf70c17-f88a-4c49-9022-f5404dd2358e)

It's working perfectly for me with `autoReloadItemOnLayout="false"`, so I'll probably just stick with that for now. But I'm interested to hear if it's just me doing something stupid haha
