### ISSUE TITLE
@nativescript/core/utils/utils doesn't exist for NativeScript 8.4.1

### ISSUE THREAD

**Issue by serrg1994** [nativescript-community/ui-collectionview#45]
After upgrading to NativeScript 8.4.1 I cannot run my project because of these error. I also had in my own code updated path for utils and now path should be `@nativescript/core/utils` instead of `@nativescript/core/utils/utils`

**Comment by farfromrefug** [comment]
@serrg1994 a new update is already released ;) (just)

**Comment by NathanWalker** [comment]
Fix was published in [4.0.64](https://github.com/nativescript-community/ui-collectionview/commit/754eefec864f9d0056903a9fad9140cfae50d80c)
