### ISSUE TITLE
Import this plugin from other.

### ISSUE THREAD

**Issue by wuilmerj24** [nativescript-community/ui-collectionview#52]
Sorry for making an issue with this, but I don't know if this can be done.
Is it possible to use this plugin from another one?
I am creating a plugin to embed a gallery within the app.
Is this possible to do?

**Comment by farfromrefug** [comment]
I dont any reason why you could not

**Comment by wuilmerj24** [comment]
@farfromrefug Hello. Thanks, I don't have much experience in ns plugins. But I don't know if you could help me how I could install it and how I could create a view from just ts or what do you recommend? 
Thanks.

**Comment by farfromrefug** [comment]
@wuilmerj24 it depends on what you want to do. Start your plugin and ask for help on discord. I ll help when i can

**Comment by wuilmerj24** [comment]
@farfromrefug ok I understand. I asked for discord 1 month ago and no answers or help hahaha What I want is to be able to make a gallery of images/videos within the application, without having to open an intent. Something like this https://github.com/LuckSiege/PictureSelector.

**Comment by farfromrefug** [comment]
@wuilmerj24 you need to work on this first so that people can help you after. 
I ll close this issue as it is not really an issue. You can keep that discussion on discord
