### ISSUE TITLE
iOS crash when async loading items into ObservableArray

### ISSUE THREAD

**Issue by felixkrautschuk** [nativescript-community/ui-collectionview#55]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

When loading data items asynchronously (REST api, ...) and pushing them into the ObservableArray of the collectionview, the app crashes on iOS with the following message:
`Uncaught Error: attempt to insert item 0 into section 0, but there are only 0 sections after the update`

When I add the items synchronously (without any delay), the crash does not occur.

### Which platform(s) does your issue occur on?
- iOS
- iOS 16.2 (also all versions to 13.7..)
- emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.4.0
- Cross-platform modules: 8.4.7
- Runtime(s): ios 8.4.1
- Plugin(s): collectionview 4.0.70

### Please, tell us how to recreate the issue in as much detail as possible. 
- open the sample app provided above
- tap the button to navigate to the page with collectionview
- items are loaded -> crash

### Is there any code involved? 
XML
```
<cv:CollectionView loaded="onCollectionViewLoaded"
                           items="{{ items }}"
                           itemTap="onItemTap"
                           visibility="{{ isLoading ? 'collapse' : 'visible' }}">
            <cv:CollectionView.itemTemplate>
                <StackLayout padding="12" borderBottomWidth="1" borderBottomColor="#656565">
                    <Label fontSize="20" text="{{ id }}"/>
                    <Label fontSize="15" text="{{ title }}" textWrap="true"/>
                </StackLayout>
            </cv:CollectionView.itemTemplate>
</cv:CollectionView>
```

TS
```
...
const myItems = [{ id: 1, title "My title 1" }, { id: 2, title "My title 2" }, ... }];
vm.set("isLoading", true);

setTimeout(() => {
      vm.get("items").splice(0, vm.get("items").length);
      vm.get("items").push(...myItems);

      vm.set("isLoading", false);
, 2000);
...

```

Full sample app:
[ns-collectionview.zip](https://github.com/nativescript-community/ui-collectionview/files/10982186/ns-collectionview.zip)

**Comment by farfromrefug** [comment]
@felixkrautschuk thanks for the great repro example! i have been hunting this one for a while. The  fix has been published.

**Comment by felixkrautschuk** [comment]
@farfromrefug now it is working, thank you for the fix!
