### ISSUE TITLE
iOS wrong item heights / ovrlapping items since 4.0.72 with dynamic cell size

### ISSUE THREAD

**Issue by felixkrautschuk** [nativescript-community/ui-collectionview#57]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

After upgrading the plugin from 4.0.71 to 4.0.72, we see layout issues when having items with dynamic cell sizes.
It is similar to an already existing issue in the current RadListView version. But in collectionview, the issue only (mostly) occurs on scrolling the list.

https://user-images.githubusercontent.com/6443021/228277852-473d7379-2c10-4c8d-8c13-2da96997ab47.mov

I double checked, that the issue did not occur in the previous plugin version.

### Which platform(s) does your issue occur on?
- iOS
- iOS 16.2 (also tested 14, 15)
- emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.4.0
- Cross-platform modules: 8.4.7
- Runtime(s): 8.4.1
- Plugin(s): collectionview 4.0.72

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Follow the steps from the video inside the provided sample app.

### Is there any code involved? 
[ns-collectionview.zip](https://github.com/nativescript-community/ui-collectionview/files/11090891/ns-collectionview.zip)

**Comment by farfromrefug** [comment]
@felixkrautschuk sorry about the regression. Will fix it tomorrow

**Comment by farfromrefug** [comment]
@felixkrautschuk should be fixed in 4.0.73

**Comment by felixkrautschuk** [comment]
@farfromrefug Now it is working, thank you very much for the quick fix!
