### ISSUE TITLE
Different behaviour 4.x 5.x refreshVisibleItems/refresh

### ISSUE THREAD

**Issue by jcassidyav** [nativescript-community/ui-collectionview#59]
### Which platform(s) does your issue occur on?
- iOS
- emulator or device. both

### Please, tell us how to recreate the issue in as much detail as possible. 

Run the attached project and tap either refresh or refreshVisibleItems a few times.

The ObservableArray bound to the collectionView does not change, but you can see the background colours of the cells fluctuates.

switching collectionView to 4.x you don't see this behaviour.

### Is there any code involved? 
This is a sample project: [testlist.zip](https://github.com/nativescript-community/ui-collectionview/files/11215155/testlist.zip)

**Comment by farfromrefug** [comment]
@jcassidyav can you try 5.0.3 should be fixed

**Comment by jcassidyav** [comment]
@farfromrefug Yes that fixes the issue in the sample, however it then allows me to illustrate the following issue:

In this project [testlist2.zip](https://github.com/nativescript-community/ui-collectionview/files/11232015/testlist2.zip), the 3rd item should change height ( as a portion is collapsed based on a toggled value) when the refresh/refreshVisible items is clicked.

When you click refresh it does, but clicking refreshVisibleItems it does not.  Shouldn't both methods have the same visible effects?

**Comment by farfromrefug** [comment]
@jcassidyav thanks a lot I ll fix it. Correspond to another user issue. 
Sorry I worked on making the iOS version much faster, but there were some regressions...

**Comment by farfromrefug** [comment]
@jcassidyav actually that resize but was always there. It also exists in 4.x.
I ll look a bit at `refreshVisibleItems` but what you are trying to do is the wrong way to do it. If you want to update a single item (even size) you should use `this.items.setItem(2, item)`. And it will only update the changed item which will be much faster than `refreshVisibleItems`
Though i see an issue with it in 5.x!

**Comment by farfromrefug** [comment]
@jcassidyav here this case of `refreshVisibleItems` does not work either in 4.x
But the setItem cell size update is broken in 5.x!

**Comment by farfromrefug** [comment]
@jcassidyav ok i found the issue and it does not seem to be an issue in the plugin but in the core xml.
When you update an item with `setItem` then a cell measurement is called then a layout.
In the cell measurement we update the cell binding context but the view property is not updated yet (might be async) so the measurement is wrong (still collapsed when should be visible). but then in cell layout it works and is updated

I tested with svelte and vue and they work correctly in cell measurement

**Comment by jcassidyav** [comment]
@farfromrefug ah ok that makes sense now since my app is angular it probably explains 4.x working there as is as well, Will test and let you know.

**Comment by jcassidyav** [comment]
@farfromrefug I think that PR should fix the issue ( it just replicates what happens when the ObservableArray is updated ).

I also confirmed 'setItem' works as expected in a small angular exception. so with this PR I think it refreshes correctly in all cases.
