### ISSUE TITLE
[Feature] Does any one work one Pull To Refresh ?

### ISSUE THREAD

**Issue by kefahB** [nativescript-community/ui-collectionview#62]
Hi @farfromrefug,

Does any one work one Pull To Refresh feature ?

By the way I sent you a msg on Linkedin, need to speak with you :)

**Comment by farfromrefug** [comment]
@kefahB you can use `@nativescript-community/ui-pulltorefresh` . As for linkedin i dont really use it anymore you can contact me either on discord or by mail: contact at akylas.fr
