### ISSUE TITLE
isListLikeIterable not found

### ISSUE THREAD

**Issue by SeanKelly369** [nativescript-community/ui-collectionview#64]
Using Angular 13.3.0, 5.0.1 of ui-collectionview builds fine, but since 5.0.2 a breaking change was introduced, at least for Angular 13 and earlier.

In the file src/collectionview/angular/collectionview-comp.ts , the changes made to the import of isListLikeIterable result in it not being found in Angular 13.3.0

Code changes made can be found at ->
https://github.com/nativescript-community/ui-collectionview/compare/v5.0.1...v5.0.2#diff-cf9b2ba7597172821a0ced378be55200ba900f24e5d7808ae649f7621e8963bb

**Comment by farfromrefug** [comment]
@SeanKelly369 this was asked for angular 15.x. Not sure I can do anything about it. I guess you either upgrade angular or use older version (I dont use angular)

**Comment by SeanKelly369** [comment]
@farfromrefug no bother, I'm able to get it to run on Angular 13.
