### ISSUE TITLE
version 5.3.3 overlap in ios not working correctly with reorderEnabled

### ISSUE THREAD

**Issue by vallemar** [nativescript-community/ui-collectionview#73]
With the latest version, when we have reorderEnabled and drag an item to subsequent positions, the item passes behind the lower view

https://github.com/nativescript-community/ui-collectionview/assets/15719383/489ff17d-26ec-4d3e-afe2-68908c84a027

**Comment by farfromrefug** [comment]
@vallemar OK that was bound to happen. Will fix thanks

**Comment by vallemar** [comment]
Thanks!!
