### ISSUE TITLE
CollectionView with swipemenu error in ios

### ISSUE THREAD

**Issue by vallemar** [nativescript-community/ui-collectionview#75]
I have updated the version of collectionView from 5.3.3 to 5.3.7, and now on iOS I have this strange behavior when using swipeMenu. It seems that drag is applied to another item

https://github.com/nativescript-community/ui-collectionview/assets/15719383/6907733e-9518-4e9a-86e2-aec725d30aeb

**Comment by farfromrefug** [comment]
@vallemar i tried with the demo app and i cant reproduce. Can you share a simple example (possibly vue2 ) reproducing the issue?
Thanks

**Comment by vallemar** [comment]
@farfromrefug  ok, I'll try to reproduce it with a sample in vue2

**Comment by vallemar** [comment]
@farfromrefug  fixed with 5.3.15

**Comment by farfromrefug** [comment]
@vallemar oh yes now i understand this one ! :D
