### ISSUE TITLE
itemTemplateSelector paint different with recycling

### ISSUE THREAD

**Issue by vallemar** [nativescript-community/ui-collectionview#78]
I am using the itemTemplateSelector function and when the views are recycled it seems that it takes the wrong template, there are times for some views that it takes the default one and another the custom one (I only have two templates)

One template puts the text on the left and another on the right (I could use the same template but these templates will change more over the days)

The same thing happens on iOS and Android, I'm on version `5.3.30` and I'm using the N fork

Android 

https://github.com/nativescript-community/ui-collectionview/assets/15719383/1e90120e-2b84-4111-8aab-5238bd7cf5c7

iOS

https://github.com/nativescript-community/ui-collectionview/assets/15719383/69dcb7e8-a0d8-4642-afe5-729e75131819

**Comment by farfromrefug** [comment]
@vallemar without a example project it is hard to help you. Plus i am not sure what i should see.

**Comment by vallemar** [comment]
@farfromrefug I supposed, I'll create a simple project and share it, thanks!

**Comment by vallemar** [comment]
@farfromrefug  It seems that there is something that does not work well with the selection of the template in vue3, in vue2 it works fine.

@rigor789 , could you take a look at it? I'm looking but I don't understand very well how the template selection works, although it seems "simple" I don't understand it at all

vue2 repo: https://github.com/vallemar/cvitemTemplateSelector-vue2
vue3 repo: https://github.com/vallemar/cvitemTemplateSelector-vue3

They are exactly the same

**Comment by vallemar** [comment]
Fixed in https://github.com/nativescript-community/ui-collectionview/releases/tag/v5.3.40
