### ISSUE TITLE
"CollectionViewWaterfallLayoutDelegate is not defined" for waterfall plugin on IOS, Angular 

### ISSUE THREAD

**Issue by EugeneHerasymchuk** [nativescript-community/ui-collectionview#81]
Issue appear on device for IOS, it does not appear on android emulator. 

Tbh, I wanted to recreate stackblitz for completely different issue ( when we have large list of items with different height with waterfall plugin - opening detail view of item after scrolling a bit and then getting back to the list - opens list on scrolled state, ordering the list only for this specific viewport and then scrolling up it reorders list dynamically, items are jumping from place to place ) 

### Which platform(s) does your issue occur on?
- iOS v17.5.1
- device

### Please, provide the following version numbers that your issue occurs with:
- Plugin: waterfall@5.3.40
- 
### Please, tell us how to recreate the issue in as much detail as possible. 

https://stackblitz.com/edit/nativescript-stackblitz-templates-ceomer?file=package.json,src%2Fapp%2Fapp.module.ts&title=NativeScript%20Starter%20Angular

![telegram-cloud-photo-size-2-5364344192437968069-y](https://github.com/user-attachments/assets/55bb4fa5-96f0-4c6c-aed8-1cfa41312076)

**Comment by farfromrefug** [comment]
@EugeneHerasymchuk It works fine here. Seems like a cocoapod issue. Make sure cocoapod is run correctly and that the plugin pod dependency is installed. You can try to clean and build again
