### ISSUE TITLE
Vue3: globalProperties are not passed to components in CollectionView templates

### ISSUE THREAD

**Issue by MrSnoozles** [nativescript-community/ui-collectionview#82]
### Which platform(s) does your issue occur on?
- Both latest iOS & Android, on all devices

### Please, tell us how to recreate the issue in as much detail as possible. 
When a CollectionView template has a component that uses globalProperties, the value of that property is undefined.

### Is there any code involved? 
https://stackblitz.com/edit/nativescript-vue-nativescript-vue-8wmhut?file=src%2Fapp.ts
-> in components/Home.vue the value of  app.config.globalProperties.$TEXT is set ✔
-> in components/Detail.vue the value of app.config.globalProperties.$TEXT is undefined ❌

**Comment by farfromrefug** [comment]
@vallemar maybe you can have a look at this? i dont use vue3 so would not know where to start

**Comment by vallemar** [comment]
@farfromrefug yes, I can check this!

**Comment by MrSnoozles** [comment]
@vallemar Thanks so much!
@farfromrefug Could you release a version that contains this fix?

**Comment by farfromrefug** [comment]
@MrSnoozles done!
