### ISSUE TITLE
scrollbar will go to the top after loading more in iOS

### ISSUE THREAD

**Issue by liuy97** [nativescript-community/ui-collectionview#86]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
when list reaches the bottom, app will load more items. If adding header into item array, this will result in scrollbar on the top.
```
 this.items = items.reduce((prev, current) => {
            prev.push({
              role: "header",
              name: current.date.toDateString(),
            });
            prev.push(current);
            return prev;
          }, []);
```
If removing header, it works fine.
```
 this.items = items.reduce((prev, current) => {
            prev.push(current);
            return prev;
          }, []);
```
### Which platform(s) does your issue occur on?
- iOS
- iOS 17.5
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
- 8.7.2
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/@nativescript/core/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
 "@nativescript/ios": "8.7.2",
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
scroll to the bottom, and the scrollbar will reach the top

### Is there any code involved? 
 - [demo.zip](https://github.com/user-attachments/files/17676257/demo.zip)
 provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by farfromrefug** [comment]
@liuy97 i tested your demo and it works fine here on ios 18. Not sure what the issue is on your side

**Comment by liuy97** [comment]
https://github.com/user-attachments/assets/c5c4b9f9-8e1b-4224-8add-e4bc7d76500f

@farfromrefug , thanks. I uploaded a video record for this bug. I run it in iOS 17.5.

**Comment by farfromrefug** [comment]
@liuy97 well this is the normal behavior. You are overwriting the items array everytime which triggers a refresh on the collectionview thus scrolling back to the top. Not sure why i see different behavior on ios 18, but all seems good to me

**Comment by liuy97** [comment]
@farfromrefug , It does not trigger a refresh in android, and it will not in iOS without header template in the array.

I get the same result without update array reference in iOS. It seems to me there are inconsistent between iOS and Android, between single templates and two templates in iOS. I will try iOS 18 see whether the demo works.

```
ngOnInit(): void {
    this.items = [];
    this.itemService.items$
      .pipe(
        debounceTime(200),
        tap((items) => {
          this.items.splice(
            0,
            this.items.length,
            ...items.reduce((prev, current) => {
              prev.push({
                role: "header",
                name: current.date.toDateString(),
              });
              prev.push(current);
              return prev;
            }, [])
          );
        })
      )
      .subscribe();
  }
```

**Comment by liuy97** [comment]
@farfromrefug , App still goes to the top in iOS 18.1 sometimes, after loading more.
https://github.com/user-attachments/assets/1ce4e45c-471d-44a0-a811-fc72643bfe1e

I have updated loading more which only push new items into the array.
```
import { Component, OnInit } from "@angular/core";
import { BehaviorSubject, debounceTime, tap } from "rxjs";
import { CollectionView } from "@nativescript-community/ui-collectionview";
import { sub } from "date-fns";

import { Item } from "./item";

@Component({
  selector: "ns-items",
  templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {
  private itemsSubject = new BehaviorSubject<Array<Item>>([]);
  items: Array<Item>;
  collectionView: CollectionView;

  ngOnInit(): void {
    this.onLoadMoreItems();
    this.itemsSubject
      .pipe(
        debounceTime(100),
        tap((items) => {
          this.items = items;
        })
      )
      .subscribe();
  }

  onScroll(e) {
    this.collectionView = e.object;
  }

  gotoTop() {
    if (this.collectionView) {
      this.collectionView.scrollToOffset(0);
    }
  }

  onLoadMoreItems(): void {
    const items = this.itemsSubject.getValue();
    const len = items.length;
    for (let i = len; i < len + 20; i++) {
      items.push({
        id: i,
        name: "name " + i,
        role: "header",
        date: sub(new Date(), { days: i }),
      });
      items.push({
        id: i,
        name: "name " + i,
        role: "item",
        date: sub(new Date(), { days: i }),
      });
    }
    this.itemsSubject.next(items);
  }

  templateSelector(item: any, index: number, items: any) {
    return item.role;
  }
}

```

**Comment by farfromrefug** [comment]
@liuy97 sorry it is too difficult to debug with an angular app. If you can reproduce your issue in a vue/core app i can look at it

**Comment by liuy97** [comment]
@farfromrefug , I try to create a demo using Nativescript core without angular, which works fine. I compared difference between them. I find that **ObservableArray** for dynamic items will help the demo in Nativescript angular too. Thanks for your help, and I close this issue.
